# Generated by Django 2.2.6 on 2019-11-02 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
